# -*- coding: utf-8 -*-
"""señales_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aVrAIOx0NtEGYhhOU5YvmCU1XETfk_82

## 🔹**CARGA Y ACCESO AL DATASET**
"""

from google.colab import files
files.upload()

"""Se configuró el acceso a Kaggle creando la carpeta correspondiente y asignando los permisos necesarios al archivo de credenciales."""

!mkdir ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

"""Se instaló la librería Kaggle y se descargó el dataset de reconocimiento de género por voz.

"""

!pip install kaggle
!kaggle datasets download -d murtadhanajim/gender-recognition-by-voiceoriginal

"""## 🔹 **Descompresión de datos**

Se descomprimió el dataset descargado para acceder a los archivos de audio.
"""

!unzip gender-recognition-by-voiceoriginal.zip

"""## 🔹 **Exploración del dataset**"""

import os
os.listdir()

"""Se revisa la estructura del dataset y se confirma que los audios están organizados en dos carpetas: male y female. (masculino y femenino)"""

import os
os.listdir("data")

"""
Se cargan los nombres de los archivos de audio de cada carpeta y se cuenta la cantidad de muestras disponibles para mujeres y hombres."""

female_files = os.listdir("data/female")
male_files = os.listdir("data/male")

print("Audios mujer:", len(female_files))
print("Audios hombre:", len(male_files))
print("Ejemplo mujer:", female_files[:5])
print("Ejemplo hombre:", male_files[:5])

"""## 🔹 **Preparación de datos para el modelo**

Se generan las rutas completas de los archivos WAV para poder cargarlos y procesarlos posteriormente.
"""

import random
from sklearn.model_selection import train_test_split

female_paths = ["data/female/" + f for f in female_files if f.endswith(".wav")]
male_paths = ["data/male/" + f for f in male_files if f.endswith(".wav")]

random.seed(42)

female_sample = random.sample(female_paths, 100)
male_sample = random.sample(male_paths, 100)

X = female_sample + male_sample
y = [0]*100 + [1]*100   # 0 = mujer, 1 = hombre

print("Total audios:", len(X))
print("Total etiquetas:", len(y))

"""División de los datos (entrenamiento/ validacion / prueba)"""

X_temp, X_test, y_temp, y_test = train_test_split(
    X, y, test_size=0.10, stratify=y, random_state=42
)

X_train, X_val, y_train, y_val = train_test_split(
    X_temp, y_temp, test_size=40, stratify=y_temp, random_state=42
)

print("Entrenamiento:", len(X_train))
print("Validación:", len(X_val))
print("Prueba final:", len(X_test))

"""Procesamiento de audio"""

import librosa
import numpy as np

"""## 🔹**Conversión de audio a espectrograma**"""

def audio_to_melspectrogram(path, max_pad_len=70):
    audio, sr = librosa.load(path, sr=22050)
    mel = librosa.feature.melspectrogram(y=audio, sr=sr, n_mels=64)
    mel_db = librosa.power_to_db(mel, ref=np.max)

    if mel_db.shape[1] < max_pad_len:
        pad_width = max_pad_len - mel_db.shape[1]
        mel_db = np.pad(mel_db, pad_width=((0,0), (0,pad_width)), mode='constant',constant_values=-80)
    else:
        mel_db = mel_db[:, :max_pad_len]

    return mel_db

X_train_cnn = np.array([audio_to_melspectrogram(p) for p in X_train])
X_val_cnn = np.array([audio_to_melspectrogram(p) for p in X_val])
X_test_cnn = np.array([audio_to_melspectrogram(p) for p in X_test])

X_train_cnn = X_train_cnn[..., np.newaxis]
X_val_cnn = X_val_cnn[..., np.newaxis]
X_test_cnn = X_test_cnn[..., np.newaxis]

y_train = np.array(y_train)
y_val = np.array(y_val)
y_test = np.array(y_test)

print(X_train_cnn.shape)

import matplotlib.pyplot as plt

# Elegir un audio de ejemplo
audio_ejemplo = X_train[100]


visual_max_pad_len = 70 # Puedes ajustar este valor, por ejemplo, 60, 90, o mantener 128

# Generar espectrograma con la longitud de padding ajustada para el ejemplo
spec = audio_to_melspectrogram(audio_ejemplo, max_pad_len=visual_max_pad_len)

# Mostrar imagen
plt.figure(figsize=(6,4))
import librosa.display

plt.figure(figsize=(6,4))

librosa.display.specshow(
    spec,
    sr=22050,
    x_axis='time',
    y_axis='hz',
    cmap='magma'
)

plt.title("Espectrograma en Hz")
plt.xlabel("Tiempo")
plt.ylabel("Frecuencia (Hz)")
plt.colorbar(format='%+2.0f dB')
plt.show()

"""140 imagenes, 64 filas (alto) → frecuencias, 70 columnas (ancho) → tiempo, 1 canal (como imagen en escala de grises).
Amarillos sonidos fuertes, Verde sonido medios y morados o azul sonidos debiles. Mel = frecuencia percibida por humanos

# **Espectro de frecuencia**
"""



import numpy as np
import matplotlib.pyplot as plt
import librosa
import librosa.display # Ensure librosa.display is available for plotting audio waveforms

# Choose an example audio file path from the training set
# Assuming X_train is available from previous cells
# You can change the index to try different audio files, e.g., X_train[0], X_train[1], etc.
# Using the same audio_ejemplo that was used for the spectrogram

# Define audio_ejemplo to resolve NameError, using an example from X_train
audio_ejemplo = X_train[100] # Using the same index as where it was previously defined

audio_file_path = audio_ejemplo

print(f"Processing audio file: {audio_file_path}")

# Load the audio file
audio, sr = librosa.load(audio_file_path, sr=22050) # sr=22050 is commonly used for audio processing

# --- 1. Plot Original Audio Waveform ---
plt.figure(figsize=(12, 4))
librosa.display.waveshow(y=audio, sr=sr)
plt.title('Audio Waveform (Time Domain)')
plt.xlabel('Time (s)')
plt.ylabel('Amplitude')
plt.grid(True)
plt.tight_layout()
plt.show()

# --- 2. Compute DFT (using FFT algorithm) and plot Magnitude Spectrum ---

# Number of samples in the audio signal
N = len(audio)

# Compute the Fast Fourier Transform (FFT) which is an efficient algorithm for DFT
yf = np.fft.fft(audio)

# Compute the corresponding frequencies
# The frequencies are symmetric around 0, from -sr/2 to sr/2
xf = np.fft.fftfreq(N, 1 / sr)

# We are interested in the magnitude of the positive frequency components
# The FFT output is symmetric, so we only take the first half (up to N//2)
# Multiply by 2.0/N to normalize the magnitude (excluding DC and Nyquist if N is even)
yf_magnitude = 2.0/N * np.abs(yf[0:N//2])
xf_positive = xf[0:N//2]

# Plot the Magnitude Spectrum
plt.figure(figsize=(12, 4))
plt.plot(xf_positive, yf_magnitude)
plt.title('Magnitude Spectrum (DFT/FFT - Frequency Domain)')
plt.xlabel('Frequency (Hz)')
plt.ylabel('Magnitude')
plt.grid(True)
plt.xlim(0, sr/2) # Limit x-axis to Nyquist frequency (max meaningful frequency)
plt.tight_layout()
plt.show()

"""La forma de onda muestra cómo varía la amplitud de la voz en el tiempo (silencios, intensidad), mientras que el espectro FFT revela las frecuencias que la componen, donde los picos dominantes permiten distinguir voces masculinas (85–180 Hz) de femeninas (165–255 Hz).

# **Análisis básico de propiedades de la señal de audio**
"""

print("Duración:", len(audio)/sr)
print("Canales:", 1)
print("Amplitud máxima:", np.max(np.abs(audio)))

"""La señal analizada tiene una duración de 3.95 segundos, lo que representa el tiempo total de la grabación, y un solo canal (mono), indicando que toda la información de audio está contenida en una única secuencia temporal. La amplitud máxima de 0.6497705 refleja la mayor intensidad alcanzada por la señal, siendo un parámetro clave para evaluar su nivel de energía y posible normalización antes del procesamiento.

##  🔹 **Construcción del modelo CNN**
"""

from tensorflow.keras import models, layers

cnn_model = models.Sequential([
    layers.Conv2D(32, (3,3), activation='relu', input_shape=(64,70,1)),
    layers.MaxPooling2D((2,2)),

    layers.Conv2D(64, (3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),

    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(1, activation='sigmoid')
])

cnn_model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

cnn_model.summary()

"""# 🔹 **Entrenamiento del modelo CNN**"""

history_cnn = cnn_model.fit(
    X_train_cnn, y_train,
    validation_data=(X_val_cnn, y_val),
    epochs=10,
    batch_size=16
)

import matplotlib.pyplot as plt

# Obtener los datos de historial para el modelo CNN
acc_cnn = history_cnn.history['accuracy']
val_acc_cnn = history_cnn.history['val_accuracy']
epochs_range = range(len(acc_cnn))

plt.figure(figsize=(8, 6))

# Gráfico para el modelo CNN
plt.plot(epochs_range, acc_cnn, label='Precisión de Entrenamiento CNN')
plt.plot(epochs_range, val_acc_cnn, label='Precisión de Validación CNN')
plt.legend(loc='lower right')
plt.title('Precisión de Entrenamiento y Validación del Modelo CNN')
plt.xlabel('Época')
plt.ylabel('Precisión')
plt.grid(True)

plt.tight_layout()
plt.show()

import numpy as np
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

# Obtener las predicciones del modelo CNN en el conjunto de prueba
cnn_predictions = cnn_model.predict(X_test_cnn)

# Convertir las predicciones a clases binarias (0 o 1)
# Un umbral común para una activación sigmoide es 0.5
cnn_pred_classes = (cnn_predictions > 0.5).astype(int)

# Calcular la matriz de confusión
cm_cnn = confusion_matrix(y_test, cnn_pred_classes)

# Mostrar la matriz de confusión
disp = ConfusionMatrixDisplay(confusion_matrix=cm_cnn, display_labels=['Mujer', 'Hombre'])
disp.plot(cmap=plt.cm.Blues)
plt.title('Matriz de Confusión del Modelo CNN')
plt.xlabel('Etiqueta Predicha')
plt.ylabel('Etiqueta Verdadera')
plt.show()

print("Matriz de Confusión del Modelo CNN:")
print(cm_cnn)
print("\nDonde:")
print("  - True Negative (TN):", cm_cnn[0, 0], "(Mujeres clasificadas correctamente como Mujer)")
print("  - False Positive (FP):", cm_cnn[0, 1], "(Hombres clasificados incorrectamente como Mujer)")
print("  - False Negative (FN):", cm_cnn[1, 0], "(Mujeres clasificadas incorrectamente como Hombre)")
print("  - True Positive (TP):", cm_cnn[1, 1], "(Hombres clasificadas correctamente como Hombre)")

"""## 🔹 **Prueba final del modelo CNN con un audio nuevo**"""

cnn_loss, cnn_acc = cnn_model.evaluate(X_test_cnn, y_test)
print("Precisión final CNN:", cnn_acc)

"""**cnn_loss** qué tanto se equivoca ; **cnn_acc**
qué tan preciso es
"""

# ================= PRUEBA FINAL CNN =================

# Elegir un audio de prueba (del conjunto que el modelo NO vio)
audio_prueba = X_test[1]

print("Audio usado:", audio_prueba)

# Convertir audio igual que en entrenamiento
spec = audio_to_melspectrogram(audio_prueba)
spec = spec[np.newaxis, ..., np.newaxis]

# Predicción
pred = cnn_model.predict(spec)

print("Valor predicción:", pred)

# Resultado interpretado
if pred > 0.5:
    print("Predicción CNN: Hombre")
else:
    print("Predicción CNN: Mujer")

# Mostrar etiqueta real
if "female" in audio_prueba:
    print("Etiqueta real: Mujer")
else:
    print("Etiqueta real: Hombre")

from IPython.display import Audio
Audio(audio_prueba)

"""## **Modelo RNN** 🌸

🔹 Preparación de datos para el modelo RNN - RNN procesa la señal como una secuencia temporal, manteniendo memoria de los valores anteriores para entender la evolución del audio.”

En esta sección los audios se convierten en características MFCC, las cuales representan el sonido como una secuencia de valores. Esta representación es adecuada para modelos RNN porque permite analizar cómo cambia la voz a través del tiempo.
"""

def audio_to_mfcc(path, max_pad_len=130):
    audio, sr = librosa.load(path, sr=22050)
    mfcc = librosa.feature.mfcc(y=audio, sr=sr, n_mfcc=13)

    if mfcc.shape[1] < max_pad_len:
        pad_width = max_pad_len - mfcc.shape[1]
        mfcc = np.pad(mfcc, pad_width=((0,0), (0,pad_width)), mode='constant')
    else:
        mfcc = mfcc[:, :max_pad_len]

    return mfcc

""" **Conversión de audios a MFCC** son una representación numérica del audio que captura las características más importantes de la voz humana."""

X_train_rnn = np.array([audio_to_mfcc(p) for p in X_train])
X_val_rnn = np.array([audio_to_mfcc(p) for p in X_val])
X_test_rnn = np.array([audio_to_mfcc(p) for p in X_test])

print("Train RNN:", X_train_rnn.shape)
print("Val RNN:", X_val_rnn.shape)
print("Test RNN:", X_test_rnn.shape)

"""# 🔹 **Construcción y configuración del modelo RNN**"""

from tensorflow.keras import models, layers

rnn_model = models.Sequential([
    layers.LSTM(64, input_shape=(13,130)),
    layers.Dense(32, activation='relu'),
    layers.Dense(1, activation='sigmoid')
])

rnn_model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

rnn_model.summary()

"""# 🔹 **Entrenamiento del modelo RNN**"""

history_rnn = rnn_model.fit(
    X_train_rnn, y_train,
    validation_data=(X_val_rnn, y_val),
    epochs=10,
    batch_size=16
)

import matplotlib.pyplot as plt

# Obtener los datos de historial para el modelo RNN
acc_rnn = history_rnn.history['accuracy']
val_acc_rnn = history_rnn.history['val_accuracy']
epochs_range = range(len(acc_rnn))

plt.figure(figsize=(8, 6))

# Gráfico para el modelo RNN
plt.plot(epochs_range, acc_rnn, label='Precisión de Entrenamiento RNN')
plt.plot(epochs_range, val_acc_rnn, label='Precisión de Validación RNN')
plt.legend(loc='lower right')
plt.title('Precisión de Entrenamiento y Validación del Modelo RNN')
plt.xlabel('Época')
plt.ylabel('Precisión')
plt.grid(True)

plt.tight_layout()
plt.show()

import numpy as np
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

# Obtener las predicciones del modelo RNN en el conjunto de prueba
rnn_predictions = rnn_model.predict(X_test_rnn)

# Convertir las predicciones a clases binarias (0 o 1)
# Un umbral común para una activación sigmoide es 0.5
rnn_pred_classes = (rnn_predictions > 0.5).astype(int)

# Calcular la matriz de confusión
cm_rnn = confusion_matrix(y_test, rnn_pred_classes)

# Mostrar la matriz de confusión
disp = ConfusionMatrixDisplay(confusion_matrix=cm_rnn, display_labels=['Mujer', 'Hombre'])
disp.plot(cmap=plt.cm.Blues)
plt.title('Matriz de Confusión del Modelo RNN')
plt.xlabel('Etiqueta Predicha')
plt.ylabel('Etiqueta Verdadera')
plt.show()

print("Matriz de Confusión del Modelo RNN:")
print(cm_rnn)
print("\nDonde:")
print("  - True Negative (TN):", cm_rnn[0, 0], "(Mujeres clasificadas correctamente como Mujer)")
print("  - False Positive (FP):", cm_rnn[0, 1], "(Hombres clasificados incorrectamente como Mujer)")
print("  - False Negative (FN):", cm_rnn[1, 0], "(Mujeres clasificadas incorrectamente como Hombre)")
print("  - True Positive (TP):", cm_rnn[1, 1], "(Hombres clasificadas correctamente como Hombre)")

rnn_loss, rnn_acc = rnn_model.evaluate(X_test_rnn, y_test)
print("Precisión final RNN:", rnn_acc)

# PRUEBA FINAL RNN

audio_prueba = X_test[10]

print("Audio usado:", audio_prueba)

mfcc = audio_to_mfcc(audio_prueba)
mfcc = mfcc[np.newaxis, ...]

pred = rnn_model.predict(mfcc)

print("Valor predicción:", pred)

if pred > 0.5:
    print("Predicción RNN: Hombre")
else:
    print("Predicción RNN: Mujer")

if "female" in audio_prueba:
    print("Etiqueta real: Mujer")
else:
    print("Etiqueta real: Hombre")

from IPython.display import Audio
Audio(audio_prueba)